"uese strict"// it tells the os to use the latest version 
console.log("boom baam beep");
 
let name ="jrus";
let age =14;
// NUMBER => 2 to power 53
// bigint
// string=> ""
// booleam=> true/false
// null=> standalone value
// undefined=> jab koii value assign na hui ho
// symbol => unique 
// object {null is also a boject}{if we print console.log(typeof null) => object}
// hdhrgyrfv
// gytgytftrresx
//GYTFRSEWAZS
